/**
 * Fetches the eBay API Status RSS feed and writes the latest items to docs/API_STATUS.md.
 * Used by the GitHub Action to keep an in-repo snapshot. Run with: npx tsx src/scripts/update-api-status-doc.ts
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { getApiStatusFeed, type ApiStatusItem } from '@/utils/api-status-feed.js';

const DEFAULT_LIMIT = 15;
const OUT_PATH = join(process.cwd(), 'docs', 'API_STATUS.md');

function escapeCell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function buildMarkdown(items: ApiStatusItem[]): string {
  const lines: string[] = [
    '# eBay API Status (latest)',
    '',
    'Auto-updated snapshot from the [eBay API Status RSS feed](https://developer.ebay.com/rss/api-status).',
    'Full list: [developer.ebay.com/support/api-status](https://developer.ebay.com/support/api-status).',
    '',
    `*Last updated: ${new Date().toISOString()}*`,
    '',
    '| Title | API | Site | Status | Last updated | Link |',
    '|-------|-----|------|--------|--------------|------|',
  ];

  for (const item of items) {
    const link = item.link ? `[Details](${item.link})` : '';
    lines.push(
      `| ${escapeCell(item.title)} | ${escapeCell(item.api)} | ${escapeCell(item.site)} | ${escapeCell(item.status)} | ${escapeCell(item.lastUpdated)} | ${link} |`
    );
  }

  lines.push(
    '',
    '---',
    '',
    '*Generated by [ebay-mcp](https://github.com/YosefHayim/ebay-mcp) API status sync.*'
  );
  return lines.join('\n');
}

async function main(): Promise<void> {
  const { items, error } = await getApiStatusFeed({ limit: DEFAULT_LIMIT });
  if (error && items.length === 0) {
    throw new Error(`Failed to fetch API status feed: ${error}`);
  }
  const markdown = buildMarkdown(items);
  writeFileSync(OUT_PATH, markdown, 'utf8');
  console.log(`Wrote ${items.length} items to ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
