import { Effect } from 'effect';
import type { z } from 'zod';
import { zodToJsonSchema } from 'zod-to-json-schema';
import * as marketingSchemas from '@/schemas/marketing/marketing.js';
import { defineTool } from '@/tools/defineTool.js';
import type { OutputArgs } from '@/tools/definitions/types.js';
import type { ToolEntry } from '@/tools/registry.js';

const emptyResponseSchema: OutputArgs = {
  type: 'object',
  properties: {},
  description: 'Empty response on successful operation',
};

const toOutputSchema = (schema: z.ZodTypeAny, name: string): OutputArgs =>
  zodToJsonSchema(schema, { name, $refStrategy: 'none' }) as OutputArgs;

/** Marketing API tools for campaigns, ads, promotions, reports, and email campaigns. */
export const marketingEntries: ToolEntry[] = [
  defineTool({
    name: 'ebay_bulk_create_ads_by_inventory_reference',
    description: 'Bulk create ads by inventory reference through the eBay Marketing API.',
    inputSchema: marketingSchemas.bulkCreateAdsByInventoryReferenceInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.bulkCreateAdsByInventoryReferenceResponseSchema,
      'BulkCreateAdsByInventoryReferenceResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) =>
      Effect.runPromise(api.marketing.bulkCreateAdsByInventoryReference(args)),
  }),
  defineTool({
    name: 'ebay_bulk_create_ads_by_listing_id',
    description: 'Bulk create ads by listing id through the eBay Marketing API.',
    inputSchema: marketingSchemas.bulkCreateAdsByListingIdInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.bulkAdResponseSchema,
      'BulkCreateAdsByListingIdResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.bulkCreateAdsByListingId(args)),
  }),
  defineTool({
    name: 'ebay_bulk_delete_ads_by_inventory_reference',
    description: 'Bulk delete ads by inventory reference through the eBay Marketing API.',
    inputSchema: marketingSchemas.bulkDeleteAdsByInventoryReferenceInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.bulkDeleteAdsByInventoryReferenceResponseSchema,
      'BulkDeleteAdsByInventoryReferenceResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) =>
      Effect.runPromise(api.marketing.bulkDeleteAdsByInventoryReference(args)),
  }),
  defineTool({
    name: 'ebay_bulk_delete_ads_by_listing_id',
    description: 'Bulk delete ads by listing id through the eBay Marketing API.',
    inputSchema: marketingSchemas.bulkDeleteAdsByListingIdInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.bulkDeleteAdResponseSchema,
      'BulkDeleteAdsByListingIdResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.bulkDeleteAdsByListingId(args)),
  }),
  defineTool({
    name: 'ebay_bulk_update_ads_bid_by_inventory_reference',
    description: 'Bulk update ads bid by inventory reference through the eBay Marketing API.',
    inputSchema: marketingSchemas.bulkUpdateAdsBidByInventoryReferenceInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.bulkUpdateAdsByInventoryReferenceResponseSchema,
      'BulkUpdateAdsBidByInventoryReferenceResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) =>
      Effect.runPromise(api.marketing.bulkUpdateAdsBidByInventoryReference(args)),
  }),
  defineTool({
    name: 'ebay_bulk_update_ads_bid_by_listing_id',
    description: 'Bulk update ads bid by listing id through the eBay Marketing API.',
    inputSchema: marketingSchemas.bulkUpdateAdsBidByListingIdInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.bulkAdUpdateResponseSchema,
      'BulkUpdateAdsBidByListingIdResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.bulkUpdateAdsBidByListingId(args)),
  }),
  defineTool({
    name: 'ebay_bulk_update_ads_status',
    description: 'Bulk update ads status through the eBay Marketing API.',
    inputSchema: marketingSchemas.bulkUpdateAdsStatusInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.bulkAdUpdateStatusResponseSchema,
      'BulkUpdateAdsStatusResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.bulkUpdateAdsStatus(args)),
  }),
  defineTool({
    name: 'ebay_bulk_update_ads_status_by_listing_id',
    description: 'Bulk update ads status by listing id through the eBay Marketing API.',
    inputSchema: marketingSchemas.bulkUpdateAdsStatusByListingIdInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.bulkAdUpdateStatusByListingIdResponseSchema,
      'BulkUpdateAdsStatusByListingIdResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.bulkUpdateAdsStatusByListingId(args)),
  }),
  defineTool({
    name: 'ebay_get_ads',
    description: 'Get ads through the eBay Marketing API.',
    inputSchema: marketingSchemas.getAdsInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.adPagedCollectionResponseSchema,
      'GetAdsResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getAds(args)),
  }),
  defineTool({
    name: 'ebay_create_ad_by_listing_id',
    description: 'Create ad by listing id through the eBay Marketing API.',
    inputSchema: marketingSchemas.createAdByListingIdInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.createAdByListingId(args)),
  }),
  defineTool({
    name: 'ebay_create_ads_by_inventory_reference',
    description: 'Create ads by inventory reference through the eBay Marketing API.',
    inputSchema: marketingSchemas.createAdsByInventoryReferenceInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.adReferencesSchema,
      'CreateAdsByInventoryReferenceResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.createAdsByInventoryReference(args)),
  }),
  defineTool({
    name: 'ebay_get_ad',
    description: 'Get ad through the eBay Marketing API.',
    inputSchema: marketingSchemas.getAdInputSchema.shape,
    outputSchema: toOutputSchema(marketingSchemas.adSchema, 'GetAdResponse'),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getAd(args)),
  }),
  defineTool({
    name: 'ebay_delete_ad',
    description: 'Delete ad through the eBay Marketing API.',
    inputSchema: marketingSchemas.deleteAdInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false, destructiveHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.deleteAd(args)),
  }),
  defineTool({
    name: 'ebay_delete_ads_by_inventory_reference',
    description: 'Delete ads by inventory reference through the eBay Marketing API.',
    inputSchema: marketingSchemas.deleteAdsByInventoryReferenceInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.adIdsSchema,
      'DeleteAdsByInventoryReferenceResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.deleteAdsByInventoryReference(args)),
  }),
  defineTool({
    name: 'ebay_get_ads_by_inventory_reference',
    description: 'Get ads by inventory reference through the eBay Marketing API.',
    inputSchema: marketingSchemas.getAdsByInventoryReferenceInputSchema.shape,
    outputSchema: toOutputSchema(marketingSchemas.adsSchema, 'GetAdsByInventoryReferenceResponse'),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getAdsByInventoryReference(args)),
  }),
  defineTool({
    name: 'ebay_update_bid',
    description: 'Update bid through the eBay Marketing API.',
    inputSchema: marketingSchemas.updateBidInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.updateBid(args)),
  }),
  defineTool({
    name: 'ebay_get_ad_groups',
    description: 'Get ad groups through the eBay Marketing API.',
    inputSchema: marketingSchemas.getAdGroupsInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.adGroupPagedCollectionResponseSchema,
      'GetAdGroupsResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getAdGroups(args)),
  }),
  defineTool({
    name: 'ebay_create_ad_group',
    description: 'Create ad group through the eBay Marketing API.',
    inputSchema: marketingSchemas.createAdGroupInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.createAdGroup(args)),
  }),
  defineTool({
    name: 'ebay_get_ad_group',
    description: 'Get ad group through the eBay Marketing API.',
    inputSchema: marketingSchemas.getAdGroupInputSchema.shape,
    outputSchema: toOutputSchema(marketingSchemas.adGroupSchema, 'GetAdGroupResponse'),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getAdGroup(args)),
  }),
  defineTool({
    name: 'ebay_update_ad_group',
    description: 'Update ad group through the eBay Marketing API.',
    inputSchema: marketingSchemas.updateAdGroupInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false, idempotentHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.updateAdGroup(args)),
  }),
  defineTool({
    name: 'ebay_suggest_bids',
    description: 'Suggest bids through the eBay Marketing API.',
    inputSchema: marketingSchemas.suggestBidsInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.targetedBidsPagedCollectionSchema,
      'SuggestBidsResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.suggestBids(args)),
  }),
  defineTool({
    name: 'ebay_suggest_keywords',
    description: 'Suggest keywords through the eBay Marketing API.',
    inputSchema: marketingSchemas.suggestKeywordsInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.targetedKeywordsPagedCollectionSchema,
      'SuggestKeywordsResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.suggestKeywords(args)),
  }),
  defineTool({
    name: 'ebay_clone_campaign',
    description: 'Clone campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.cloneCampaignInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.cloneCampaign(args)),
  }),
  defineTool({
    name: 'ebay_get_campaigns',
    description: 'Get campaigns through the eBay Marketing API.',
    inputSchema: marketingSchemas.getCampaignsInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.campaignPagedCollectionResponseSchema,
      'GetCampaignsResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getCampaigns(args)),
  }),
  defineTool({
    name: 'ebay_create_campaign',
    description: 'Create campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.createCampaignInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.createCampaign(args)),
  }),
  defineTool({
    name: 'ebay_get_campaign',
    description: 'Get campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.getCampaignInputSchema.shape,
    outputSchema: toOutputSchema(marketingSchemas.campaignSchema, 'GetCampaignResponse'),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getCampaign(args)),
  }),
  defineTool({
    name: 'ebay_delete_campaign',
    description: 'Delete campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.deleteCampaignInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false, destructiveHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.deleteCampaign(args)),
  }),
  defineTool({
    name: 'ebay_end_campaign',
    description: 'End campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.endCampaignInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.endCampaign(args)),
  }),
  defineTool({
    name: 'ebay_find_campaign_by_ad_reference',
    description: 'Find campaign by ad reference through the eBay Marketing API.',
    inputSchema: marketingSchemas.findCampaignByAdReferenceInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.campaignsSchema,
      'FindCampaignByAdReferenceResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.findCampaignByAdReference(args)),
  }),
  defineTool({
    name: 'ebay_get_campaign_by_name',
    description: 'Get campaign by name through the eBay Marketing API.',
    inputSchema: marketingSchemas.getCampaignByNameInputSchema.shape,
    outputSchema: toOutputSchema(marketingSchemas.campaignSchema, 'GetCampaignByNameResponse'),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getCampaignByName(args)),
  }),
  defineTool({
    name: 'ebay_launch_campaign',
    description: 'Launch campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.launchCampaignInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.launchCampaign(args)),
  }),
  defineTool({
    name: 'ebay_pause_campaign',
    description: 'Pause campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.pauseCampaignInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.pauseCampaign(args)),
  }),
  defineTool({
    name: 'ebay_resume_campaign',
    description: 'Resume campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.resumeCampaignInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.resumeCampaign(args)),
  }),
  defineTool({
    name: 'ebay_setup_quick_campaign',
    description: 'Setup quick campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.setupQuickCampaignInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.setupQuickCampaign(args)),
  }),
  defineTool({
    name: 'ebay_suggest_budget',
    description: 'Suggest budget through the eBay Marketing API.',
    inputSchema: marketingSchemas.suggestBudgetInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.suggestBudgetResponseSchema,
      'SuggestBudgetResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.suggestBudget(args)),
  }),
  defineTool({
    name: 'ebay_suggest_items',
    description: 'Suggest items through the eBay Marketing API.',
    inputSchema: marketingSchemas.suggestItemsInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.targetedAdsPagedCollectionSchema,
      'SuggestItemsResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.suggestItems(args)),
  }),
  defineTool({
    name: 'ebay_suggest_max_cpc',
    description: 'Suggest max cpc through the eBay Marketing API.',
    inputSchema: marketingSchemas.suggestMaxCpcInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.suggestMaxCpcResponseSchema,
      'SuggestMaxCpcResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.suggestMaxCpc(args)),
  }),
  defineTool({
    name: 'ebay_update_ad_rate_strategy',
    description: 'Update ad rate strategy through the eBay Marketing API.',
    inputSchema: marketingSchemas.updateAdRateStrategyInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.updateAdRateStrategy(args)),
  }),
  defineTool({
    name: 'ebay_update_bidding_strategy',
    description: 'Update bidding strategy through the eBay Marketing API.',
    inputSchema: marketingSchemas.updateBiddingStrategyInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.updateBiddingStrategy(args)),
  }),
  defineTool({
    name: 'ebay_update_campaign_budget',
    description: 'Update campaign budget through the eBay Marketing API.',
    inputSchema: marketingSchemas.updateCampaignBudgetInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.updateCampaignBudget(args)),
  }),
  defineTool({
    name: 'ebay_update_campaign_identification',
    description: 'Update campaign identification through the eBay Marketing API.',
    inputSchema: marketingSchemas.updateCampaignIdentificationInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.updateCampaignIdentification(args)),
  }),
  defineTool({
    name: 'ebay_bulk_create_keyword',
    description: 'Bulk create keyword through the eBay Marketing API.',
    inputSchema: marketingSchemas.bulkCreateKeywordInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.bulkCreateKeywordResponseSchema,
      'BulkCreateKeywordResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.bulkCreateKeyword(args)),
  }),
  defineTool({
    name: 'ebay_bulk_update_keyword',
    description: 'Bulk update keyword through the eBay Marketing API.',
    inputSchema: marketingSchemas.bulkUpdateKeywordInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.bulkUpdateKeywordResponseSchema,
      'BulkUpdateKeywordResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.bulkUpdateKeyword(args)),
  }),
  defineTool({
    name: 'ebay_get_keywords',
    description: 'Get keywords through the eBay Marketing API.',
    inputSchema: marketingSchemas.getKeywordsInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.keywordPagedCollectionResponseSchema,
      'GetKeywordsResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getKeywords(args)),
  }),
  defineTool({
    name: 'ebay_create_keyword',
    description: 'Create keyword through the eBay Marketing API.',
    inputSchema: marketingSchemas.createKeywordInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.createKeyword(args)),
  }),
  defineTool({
    name: 'ebay_get_keyword',
    description: 'Get keyword through the eBay Marketing API.',
    inputSchema: marketingSchemas.getKeywordInputSchema.shape,
    outputSchema: toOutputSchema(marketingSchemas.keywordSchema, 'GetKeywordResponse'),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getKeyword(args)),
  }),
  defineTool({
    name: 'ebay_update_keyword',
    description: 'Update keyword through the eBay Marketing API.',
    inputSchema: marketingSchemas.updateKeywordInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.updateKeywordResponseSchema,
      'UpdateKeywordResponse',
    ),
    annotations: { readOnlyHint: false, idempotentHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.updateKeyword(args)),
  }),
  defineTool({
    name: 'ebay_bulk_create_negative_keyword',
    description: 'Bulk create negative keyword through the eBay Marketing API.',
    inputSchema: marketingSchemas.bulkCreateNegativeKeywordInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.bulkCreateNegativeKeywordResponseSchema,
      'BulkCreateNegativeKeywordResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.bulkCreateNegativeKeyword(args)),
  }),
  defineTool({
    name: 'ebay_bulk_update_negative_keyword',
    description: 'Bulk update negative keyword through the eBay Marketing API.',
    inputSchema: marketingSchemas.bulkUpdateNegativeKeywordInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.bulkUpdateNegativeKeywordResponseSchema,
      'BulkUpdateNegativeKeywordResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.bulkUpdateNegativeKeyword(args)),
  }),
  defineTool({
    name: 'ebay_get_negative_keywords',
    description: 'Get negative keywords through the eBay Marketing API.',
    inputSchema: marketingSchemas.getNegativeKeywordsInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.negativeKeywordPagedCollectionResponseSchema,
      'GetNegativeKeywordsResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getNegativeKeywords(args)),
  }),
  defineTool({
    name: 'ebay_create_negative_keyword',
    description: 'Create negative keyword through the eBay Marketing API.',
    inputSchema: marketingSchemas.createNegativeKeywordInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.createNegativeKeyword(args)),
  }),
  defineTool({
    name: 'ebay_get_negative_keyword',
    description: 'Get negative keyword through the eBay Marketing API.',
    inputSchema: marketingSchemas.getNegativeKeywordInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.negativeKeywordSchema,
      'GetNegativeKeywordResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getNegativeKeyword(args)),
  }),
  defineTool({
    name: 'ebay_update_negative_keyword',
    description: 'Update negative keyword through the eBay Marketing API.',
    inputSchema: marketingSchemas.updateNegativeKeywordInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false, idempotentHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.updateNegativeKeyword(args)),
  }),
  defineTool({
    name: 'ebay_get_report',
    description: 'Get report through the eBay Marketing API.',
    inputSchema: marketingSchemas.getReportInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getReport(args)),
  }),
  defineTool({
    name: 'ebay_get_report_metadata',
    description: 'Get report metadata through the eBay Marketing API.',
    inputSchema: marketingSchemas.getReportMetadataInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.reportMetadatasSchema,
      'GetReportMetadataResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getReportMetadata(args)),
  }),
  defineTool({
    name: 'ebay_get_report_metadata_for_report_type',
    description: 'Get report metadata for report type through the eBay Marketing API.',
    inputSchema: marketingSchemas.getReportMetadataForReportTypeInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.reportMetadataSchema,
      'GetReportMetadataForReportTypeResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getReportMetadataForReportType(args)),
  }),
  defineTool({
    name: 'ebay_get_report_tasks',
    description: 'Get report tasks through the eBay Marketing API.',
    inputSchema: marketingSchemas.getReportTasksInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.reportTaskPagedCollectionSchema,
      'GetReportTasksResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getReportTasks(args)),
  }),
  defineTool({
    name: 'ebay_create_report_task',
    description: 'Create report task through the eBay Marketing API.',
    inputSchema: marketingSchemas.createReportTaskInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.createReportTask(args)),
  }),
  defineTool({
    name: 'ebay_get_report_task',
    description: 'Get report task through the eBay Marketing API.',
    inputSchema: marketingSchemas.getReportTaskInputSchema.shape,
    outputSchema: toOutputSchema(marketingSchemas.reportTaskSchema, 'GetReportTaskResponse'),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getReportTask(args)),
  }),
  defineTool({
    name: 'ebay_delete_report_task',
    description: 'Delete report task through the eBay Marketing API.',
    inputSchema: marketingSchemas.deleteReportTaskInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false, destructiveHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.deleteReportTask(args)),
  }),
  defineTool({
    name: 'ebay_create_item_price_markdown_promotion',
    description: 'Create item price markdown promotion through the eBay Marketing API.',
    inputSchema: marketingSchemas.createItemPriceMarkdownPromotionInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.createItemPriceMarkdownPromotion(args)),
  }),
  defineTool({
    name: 'ebay_get_item_price_markdown_promotion',
    description: 'Get item price markdown promotion through the eBay Marketing API.',
    inputSchema: marketingSchemas.getItemPriceMarkdownPromotionInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.itemPriceMarkdownSchema,
      'GetItemPriceMarkdownPromotionResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getItemPriceMarkdownPromotion(args)),
  }),
  defineTool({
    name: 'ebay_update_item_price_markdown_promotion',
    description: 'Update item price markdown promotion through the eBay Marketing API.',
    inputSchema: marketingSchemas.updateItemPriceMarkdownPromotionInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false, idempotentHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.updateItemPriceMarkdownPromotion(args)),
  }),
  defineTool({
    name: 'ebay_delete_item_price_markdown_promotion',
    description: 'Delete item price markdown promotion through the eBay Marketing API.',
    inputSchema: marketingSchemas.deleteItemPriceMarkdownPromotionInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false, destructiveHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.deleteItemPriceMarkdownPromotion(args)),
  }),
  defineTool({
    name: 'ebay_create_item_promotion',
    description: 'Create item promotion through the eBay Marketing API.',
    inputSchema: marketingSchemas.createItemPromotionInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.baseResponseSchema,
      'CreateItemPromotionResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.createItemPromotion(args)),
  }),
  defineTool({
    name: 'ebay_get_item_promotion',
    description: 'Get item promotion through the eBay Marketing API.',
    inputSchema: marketingSchemas.getItemPromotionInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.itemPromotionResponseSchema,
      'GetItemPromotionResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getItemPromotion(args)),
  }),
  defineTool({
    name: 'ebay_update_item_promotion',
    description: 'Update item promotion through the eBay Marketing API.',
    inputSchema: marketingSchemas.updateItemPromotionInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.baseResponseSchema,
      'UpdateItemPromotionResponse',
    ),
    annotations: { readOnlyHint: false, idempotentHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.updateItemPromotion(args)),
  }),
  defineTool({
    name: 'ebay_delete_item_promotion',
    description: 'Delete item promotion through the eBay Marketing API.',
    inputSchema: marketingSchemas.deleteItemPromotionInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false, destructiveHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.deleteItemPromotion(args)),
  }),
  defineTool({
    name: 'ebay_get_listing_set',
    description: 'Get listing set through the eBay Marketing API.',
    inputSchema: marketingSchemas.getListingSetInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.itemsPagedCollectionSchema,
      'GetListingSetResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getListingSet(args)),
  }),
  defineTool({
    name: 'ebay_get_promotions',
    description: 'Get promotions through the eBay Marketing API.',
    inputSchema: marketingSchemas.getPromotionsInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.promotionsPagedCollectionSchema,
      'GetPromotionsResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getPromotions(args)),
  }),
  defineTool({
    name: 'ebay_pause_promotion',
    description: 'Pause promotion through the eBay Marketing API.',
    inputSchema: marketingSchemas.pausePromotionInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.pausePromotion(args)),
  }),
  defineTool({
    name: 'ebay_resume_promotion',
    description: 'Resume promotion through the eBay Marketing API.',
    inputSchema: marketingSchemas.resumePromotionInputSchema.shape,
    outputSchema: emptyResponseSchema,
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.resumePromotion(args)),
  }),
  defineTool({
    name: 'ebay_get_promotion_reports',
    description: 'Get promotion reports through the eBay Marketing API.',
    inputSchema: marketingSchemas.getPromotionReportsInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.promotionsReportPagedCollectionSchema,
      'GetPromotionReportsResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getPromotionReports(args)),
  }),
  defineTool({
    name: 'ebay_get_promotion_summary_report',
    description: 'Get promotion summary report through the eBay Marketing API.',
    inputSchema: marketingSchemas.getPromotionSummaryReportInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.summaryReportResponseSchema,
      'GetPromotionSummaryReportResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getPromotionSummaryReport(args)),
  }),
  defineTool({
    name: 'ebay_get_email_campaigns',
    description: 'Get email campaigns through the eBay Marketing API.',
    inputSchema: marketingSchemas.getEmailCampaignsInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.getEmailCampaignsResponseSchema,
      'GetEmailCampaignsResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getEmailCampaigns(args)),
  }),
  defineTool({
    name: 'ebay_create_email_campaign',
    description: 'Create email campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.createEmailCampaignInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.createEmailCampaignResponseSchema,
      'CreateEmailCampaignResponse',
    ),
    annotations: { readOnlyHint: false },
    handler: (api, args) => Effect.runPromise(api.marketing.createEmailCampaign(args)),
  }),
  defineTool({
    name: 'ebay_get_email_campaign',
    description: 'Get email campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.getEmailCampaignInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.getEmailCampaignResponseSchema,
      'GetEmailCampaignResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getEmailCampaign(args)),
  }),
  defineTool({
    name: 'ebay_update_email_campaign',
    description: 'Update email campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.updateEmailCampaignInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.updateEmailCampaignResponseSchema,
      'UpdateEmailCampaignResponse',
    ),
    annotations: { readOnlyHint: false, idempotentHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.updateEmailCampaign(args)),
  }),
  defineTool({
    name: 'ebay_delete_email_campaign',
    description: 'Delete email campaign through the eBay Marketing API.',
    inputSchema: marketingSchemas.deleteEmailCampaignInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.deleteEmailCampaignResponseSchema,
      'DeleteEmailCampaignResponse',
    ),
    annotations: { readOnlyHint: false, destructiveHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.deleteEmailCampaign(args)),
  }),
  defineTool({
    name: 'ebay_get_audiences',
    description: 'Get audiences through the eBay Marketing API.',
    inputSchema: marketingSchemas.getAudiencesInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.getEmailCampaignAudiencesResponseSchema,
      'GetAudiencesResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getAudiences(args)),
  }),
  defineTool({
    name: 'ebay_get_email_preview',
    description: 'Get email preview through the eBay Marketing API.',
    inputSchema: marketingSchemas.getEmailPreviewInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.getEmailPreviewResponseSchema,
      'GetEmailPreviewResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getEmailPreview(args)),
  }),
  defineTool({
    name: 'ebay_get_email_report',
    description: 'Get email report through the eBay Marketing API.',
    inputSchema: marketingSchemas.getEmailReportInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.getEmailReportResponseSchema,
      'GetEmailReportResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.marketing.getEmailReport(args)),
  }),
  defineTool({
    name: 'ebay_find_listing_recommendations',
    description: 'Find listing recommendations through the eBay Recommendation API.',
    inputSchema: marketingSchemas.findListingRecommendationsInputSchema.shape,
    outputSchema: toOutputSchema(
      marketingSchemas.pagedListingRecommendationCollectionSchema,
      'FindListingRecommendationsResponse',
    ),
    annotations: { readOnlyHint: true },
    handler: (api, args) => Effect.runPromise(api.recommendation.findListingRecommendations(args)),
  }),
];
